name: vestasleep
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.9
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  firebase_storage: ^11.6.0
  cloud_firestore: ^4.14.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^5.0.0
  http: ^1.1.2
  flutter_native_splash: ^2.3.9
  #health: ^8.1.0
  health:
    path: ./health

  hydrated_bloc: ^9.1.3
  path_provider: ^2.1.2
  permission_handler: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
